### PR TITLE
Exit with 1 when validation failed

### PR DESCRIPTION
**Pull request by kna**
Many command exits with 1 when validation fails.
I think it is useful for sver too, in particular onCI.

### CODE REVIEW

**Review by mitoma — CHANGES_REQUESTED** [review]
Thank you for your Pull Request!
I agree with the motivation for this pull request.

However, there are some concerns.
Could you please fix it with one of the following policies?

**Pattern 1: Use struct**

The meaning is unclear if the return value is a tuple.
I want `(bool, Vec<ValidationResult>)` to be `ValidationResults`.

```rust
// struct image
pub struct ValidationResults {
    pub has_invalid: bool,
    pub results: Vec<ValidationResult>,
}
```

**Pattern 2: Keep the fix here**

ExitCode is of cli-only concern.
A fix in the validate method might be enough.

```rust
fn validate() -> anyhow::Result<()> {
    let validate_results = SverRepository::new(".")?.validate_sver_config()?;
    validate_results
        .iter()
        .for_each(|result| print!("{}", result));
    validate_results
        .iter()
        .all(|result| match result {
            ValidationResult::Valid { .. } => true,
            _ => false,
        })
        .then(|| ())
        .with_context(|| "There are some invalid configs")
}
```

**Comment by kna** [comment]
@mitoma 
Thank you for your kind review!
I updated this PR with 'Pattern 1: Use struct'.
Could you check it again?

**Review by mitoma — APPROVED** [review]
LGTM :shipit: 
Thank you for your correction.

**Comment by kna** [comment]
@mitoma 
Thank you!

**Pull request merged**
